bilstm: &bilstm
  arch: bilstm
  epochs: 20
  batch_size: 32
  lr: 0.001
  wd: 0.0001
  seed: 42
  data:
    csv_path: /home/samuel/PycharmProjects/QUB-PHEO/benchmark/datasets/subtasks_byTask_time.csv
    h5_dir:   /home/samuel/ml_projects/QUBPHEO/benchmark/landmarks
    obs_len:  60
    pred_len: 60
    stride:   15
    include_gaze: false
    include_obj_bbox: false
    include_surrogate_bbox: false

bigru:      {<<: *bilstm, arch: bigru}
tcn:        {<<: *bilstm, arch: tcn}
transformer: {<<: *bilstm, arch: transformer}
stgcn:      {<<: *bilstm, arch: stgcn}
