bilstm: &bilstm
  arch: bilstm
  epochs: 200
  batch_size: 64
  dropout: 0.2
  lr: 0.0001
  wd: 0.0001
  optim: adagrad
  grad_clip: 0.2
  loss:
    pose: 2.0
    intent: 10.0
  scheduler:
    name: cosine
    warmup_epochs: 5
    min_lr: 1e-5
  early_stopping:
    patience: 25
    min_delta: 0.003
    delta_f1: 0.005
  class_weights: True
  seed: 42
  data:
    csv_path: /home/samuel/PycharmProjects/QUB-PHEO/benchmark/datasets/subtasks_byTask_time.csv
    h5_dir:   /home/samuel/ml_projects/QUBPHEO/benchmark/landmarks
    obs_len:  60
    pred_len: 60
    stride:   15
    include_gaze: false
    include_obj_bbox: true
    include_surrogate_bbox: true
    obj_box_dim: 120
    sur_box_dim: 8

bigru:      {<<: *bilstm, arch: bigru}
tcn:        {<<: *bilstm, arch: tcn}
transformer: {<<: *bilstm, arch: transformer}
stgcn:      {<<: *bilstm, arch: stgcn}
